--- 
results_location: ../etc/runs/
project_id: phileas-1351
dataset: cloud
email_recipients:
  - d.kheyman@gmail.com
  - rashimgreat@gmail.com
email_from: rbcphileas@gmail.com
test_suite:
  - cloud: AWS
    globals:
      machine_type: t2.micro
      default_timeout: 600
      zones: us-east-1
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/AWS/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
  - cloud: GCP
    globals:
      machine_type:
        cpus: 1
        memory: 1GiB
      zones: us-east1-b
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/GCP/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
  - cloud: Rackspace
    globals:
      rack_path: ../lib/providers/Rackspace/rack
      rackspace_region: IAD
      rack_profile: phileas
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/Rackspace/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
  - cloud: Azure
    globals:
      machine_type: Small
      zones: East US
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/Azure/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
  - cloud: AliCloud
    globals:
        zones: us-east-1a
        machine_type: ecs.n1.tiny
        ali_system_disk_type: cloud_efficiency
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/AliCloud/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
